# Fundamentos COMPLETOS de DataFrames en Pandas

In [43]:
import pandas as pd
import numpy as np

## 1. Creación básica de DataFrame

In [44]:
data = {
    'Nombre': ['Ana', 'Luis', 'Marta'],
    'Edad': [23, 35, 29],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia']
}
df = pd.DataFrame(data)
df

  Nombre  Edad     Ciudad
0    Ana    23     Madrid
1   Luis    35  Barcelona
2  Marta    29   Valencia

## 2. Selección y filtrado

In [45]:
df['Nombre']
df[df['Edad'] > 25]

  Nombre  Edad     Ciudad
1   Luis    35  Barcelona
2  Marta    29   Valencia

## 3. Modificación

In [46]:
df['Salario'] = [50000, 60000, 55000]
df = df.drop(columns=['Ciudad'])
df

  Nombre  Edad  Salario
0    Ana    23    50000
1   Luis    35    60000
2  Marta    29    55000

## 4. Formas de crear DataFrames

In [47]:
# Lista de listas
data = [
    ['Ana', 23, 'Madrid'],
    ['Luis', 35, 'Barcelona']
]
pd.DataFrame(data, columns=['Nombre','Edad','Ciudad'])

  Nombre  Edad     Ciudad
0    Ana    23     Madrid
1   Luis    35  Barcelona

In [48]:
# Lista de diccionarios
data = [
    {'Nombre':'Ana','Edad':23},
    {'Nombre':'Luis','Edad':35}
]
pd.DataFrame(data)

  Nombre  Edad
0    Ana    23
1   Luis    35

In [49]:
# Desde NumPy
data = np.array([
    ['Ana',23,'Madrid'],
    ['Luis',35,'Barcelona']
])
pd.DataFrame(data, columns=['Nombre','Edad','Ciudad'])

  Nombre Edad     Ciudad
0    Ana   23     Madrid
1   Luis   35  Barcelona

In [50]:
# Desde Series
nombres = pd.Series(['Ana','Luis'])
edades = pd.Series([23,35])
pd.DataFrame({'Nombre':nombres,'Edad':edades})

  Nombre  Edad
0    Ana    23
1   Luis    35

## 5. Índices

In [51]:
df = pd.DataFrame({
    'Nombre':['Ana','Juan','Pedro'],
    'Edad':[23,25,30]
})
df.set_index('Nombre', inplace=True)
df

        Edad
Nombre
Ana       23
Juan      25
Pedro     30

In [52]:
# Reset index
df.reset_index(inplace=True)
df

  Nombre  Edad
0    Ana    23
1   Juan    25
2  Pedro    30

In [53]:
arrays = [['Ana','Ana','Luis','Luis'],['Math','Science','Math','Science']]
index = pd.MultiIndex.from_arrays(arrays, names=('Nombre','Asignatura'))
df_multi = pd.DataFrame({'Notas':[90,85,88,92]}, index=index)
df_multi

                   Notas
Nombre Asignatura
Ana    Math           90
       Science        85
Luis   Math           88
       Science        92

## 6. Atributos

In [54]:
df.shape
df.size
df.ndim
df.columns
df.index
df.dtypes

Nombre    object
Edad       int64
dtype: object

## 7. Métodos básicos

In [55]:
df.info()
df.describe()
df.head()
df.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  3 non-null      object
 1   Edad    3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

  Nombre  Edad
0    Ana    23
1   Juan    25
2  Pedro    30

In [ ]:
df['Edad'].mean()
df['Edad'].sum()
df['Edad'].max()
df['Edad'].min()

In [ ]:
df.count()

In [ ]:
df['Nombre'].value_counts()

In [ ]:
df_na = pd.DataFrame({'Nombre':['Ana','Luis',None],'Edad':[23,None,29]})
df_na.dropna()
df_na.fillna(0)

In [ ]:
df.sort_values(by='Edad')

In [ ]:
data = {
    'Nombre':['Ana','Luis','Ana'],
    'Edad':[23,35,22],
    'Ciudad':['Madrid','Barcelona','Madrid']
}
df_group = pd.DataFrame(data)
df_group.groupby('Ciudad').mean(numeric_only=True)

## 8. loc e iloc

In [ ]:
df = pd.DataFrame({'Nombre':['Ana','Luis','Marta'],'Edad':[23,35,29]})

df.iloc[0]
df.iloc[0:2]
df.iloc[0,1]
df.iloc[0:2,0:2]

In [ ]:
df.loc[0]
df.loc[df['Edad'] > 25]
df.loc[(df['Edad'] > 25) & (df['Nombre'] == 'Luis')]

## Reflexión

El uso de DataFrames en Pandas permite organizar y analizar datos de manera eficiente. 
Facilita la manipulación de información, el filtrado, agrupamiento y análisis estadístico, mejorando la comprensión de los datos en proyectos de análisis.